#!/usr/bin/env python3
"""Write SYNC_PREFERENCES.md and USER_NOTED_FILES.md from init answers.

The agent collects 4 answers from the user (via the question tool) and passes
them in as a single JSON blob on stdin. This script writes the two markdown
files into the workspace root and backs up any pre-existing ones.

Stdin JSON shape:
{
  "workspace_root": "/path/to/repo",
  "destination":    "/path/to/repo",
  "layout":         "course-first | type-first",
  "protected_patterns":  ["my-notes-*.md", ...],   # from Q3 auto-protect
  "protected_explicit":   ["ECE327/Lectures/lec-03-mine.pdf", ...],  # from Q3 checked + Q4 free-text
  "course_mapping":  "ECE327 -> ECE327/Lectures"   # optional, free-text
}

Outputs: path of the two files written, plus any backups made.
"""
import os
import sys
import json
import shutil
from datetime import datetime


SYNC_PREF_FILE = "SYNC_PREFERENCES.md"
USER_NOTED_FILE = "USER_NOTED_FILES.md"


def backup_if_exists(root, fname):
    path = os.path.join(root, fname)
    if not os.path.exists(path):
        return None
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    bak = f"{path}.{ts}.bak"
    shutil.copy2(path, bak)
    return bak


def write_sync_preferences(root, answers):
    content = [
        "# Sync Preferences",
        f"<!-- Generated by brightspace-student-hub init — editable by hand. -->",
        f"<!-- Last updated: {datetime.now().isoformat(timespec='seconds')} -->",
        "",
        "## destination",
        answers["destination"],
        "",
        "## layout",
        answers["layout"],  # course-first | type-first
        "",
    ]

    mapping = answers.get("course_mapping", "").strip()
    if mapping:
        content += [
            "## course_mapping",
            "<!-- Optional: override default folder derivation by course. -->",
            "```",
            mapping,
            "```",
            "",
        ]

    content += [
        "## conflict_policy",
        "skip  # default — preserve existing files. change to overwrite | rename if desired.",
        "",
    ]

    path = os.path.join(root, SYNC_PREF_FILE)
    with open(path, "w") as f:
        f.write("\n".join(content))
    return path


def write_user_noted(root, answers):
    patterns = answers.get("protected_patterns", [])
    explicit = answers.get("protected_explicit", [])

    content = [
        "# Protected Files (never overwritten, regardless of conflict policy)",
        "<!-- Generated by brightspace-student-hub init — maintain by hand. -->",
        f"<!-- Last updated: {datetime.now().isoformat(timespec='seconds')} -->",
        "",
        "## patterns (auto-protect)",
        "<!-- Any file matching one of these globs is auto-protected. -->",
    ]
    if patterns:
        content += [f"- {p}" for p in patterns]
    else:
        content += ["<!-- (none) -->"]

    content += [
        "",
        "## explicit files",
        "<!-- Individual files that must never be overwritten. -->",
    ]
    if explicit:
        content += [f"- {p}" for p in explicit]
    else:
        content += ["<!-- (none) -->"]
    content += [""]

    path = os.path.join(root, USER_NOTED_FILE)
    with open(path, "w") as f:
        f.write("\n".join(content))
    return path


def main():
    answers = json.loads(sys.stdin.read())

    root = answers["workspace_root"]
    if not os.path.isdir(root):
        print(json.dumps({"error": f"not a directory: {root}"}))
        sys.exit(1)

    required = {"destination", "layout", "workspace_root"}
    missing = required - set(answers)
    if missing:
        print(json.dumps({"error": f"missing keys: {missing}"}))
        sys.exit(2)

    backups = {
        SYNC_PREF_FILE: backup_if_exists(root, SYNC_PREF_FILE),
        USER_NOTED_FILE: backup_if_exists(root, USER_NOTED_FILE),
    }

    sync_path = write_sync_preferences(root, answers)
    noted_path = write_user_noted(root, answers)

    print(json.dumps({
        "written": {
            "SYNC_PREFERENCES.md": sync_path,
            "USER_NOTED_FILES.md": noted_path,
        },
        "backups": {k: v for k, v in backups.items() if v},
    }, indent=2))


if __name__ == "__main__":
    main()